version: '3.9'

services:
  db:
    image: postgres:15
    container_name: vinylhub
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: vinylhub_api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    command: [ "npm", "start" ]

volumes:
  postgres_data: