version: '3.9'

services:
  db:
    image: postgres:15
    container_name: vinylhub
    environment:
      POSTGRES_DB: vinylhub
      POSTGRES_USER: xrendezvous
      POSTGRES_PASSWORD: Xzvv9843
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: